version: "3"
services:
  api:
    image: matthewphilipjordan/fastapi
    ports:
      - 80:8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
