name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "test_branch"

jobs:
  job1:
    environment: 
      name: testing
    env: 
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      PGADMIN_DEFAULT_EMAIL: ${{secrets.PGADMIN_DEFAULT_EMAIL}}
      PGADMIN_DEFAULT_PASSWORD: ${{secrets.PGADMIN_DEFAULT_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: FastAPI_pytest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python 3.9
        uses: actions/setup-python@v3.1.4
        with: 
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install packages
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest