name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "test_branch"

jobs:
  job1:
    runs-on: unbuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hello
        run: echo "hello"
